let inputNombre = "ingrese nombre";//**utilizar en formulario */
let inputApellido = "ingrese apellido"//**utilizar en formulario */
let mouse = document.getElementById('mouse')
// const inforNombre = document.getElementById("inforNombre")  //**para usar con la funcion VALUE (INFORMACION DE DATOS INGRESADOS) */
// const inforApellido = document.getElementById("inforApellido") //**para usar con la funcion VALUE (INFORMACION DE DATOS INGRESADOS) */
// const inforMonto = document.getElementById("inforMonto") //**para usar con la funcion VALUE (INFORMACION DE DATOS INGRESADOS) */
// const inforCuota = document.getElementById("inforCuota") //**para usar con la funcion VALUE (INFORMACION DE DATOS INGRESADOS) */
// const inforIntereses = document.getElementById("inforCuota") //**para usar con la funcion VALUE (INFORMACION DE DATOS INGRESADOS) */

const titulo = document.getElementById('titulo')
const tituloDos = document.getElementById('tituloDos')
const monto = document.getElementById('monto');
const cuotas = document.getElementById('cuotas');
const interes = document.getElementById('interes');
const btnCalcular = document.getElementById('btnCalcular');
const alerta = document.getElementById('alert-error');
const llenarTabla = document.querySelector('#lista-tabla tbody')
const irfomulario = document.getElementById('irFormulario')
const menu= document.getElementById('menu')